CREATE TABLE IF NOT EXISTS ChatsUsers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Author INTEGER NOT NULL,
    Recipient INTEGER NOT NULL,
    Message TEXT NOT NULL,
    Date TEXT NOT NULL,
    Groupe TEXT NOT NULL DEFAULT '',
    See BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (Author) REFERENCES Users(ID),
    FOREIGN KEY (Recipient) REFERENCES Users(ID)
);
